
frontend-tests:
  script:
    - apt-get update
    - apt-get install -y curl
    - curl -sL https://deb.nodesource.com/setup_10.x | bash - # npm and nodejs PPA
    - apt-get install nodejs # contains nodejs and npm
    - cd frontend
    - npm install jest
    - npm run test
    - cd ..

backend-tests:
  script:
    - apt-get update
    - apt-get install -y python3-pip
    - pip3 install -r requirements.txt
    - find . -name  '*.py' -not -path './env/*' -not -path '*/migrations/*' -exec flake8 --max-line-length=120 {} \+
    - python3 manage.py test

