# Generated by Django 2.1.5 on 2019-10-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20191030_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrheadsetrent',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
