# Generated by Django 2.1.5 on 2019-10-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_vrheadsetrent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrheadsetrent',
            name='price',
            field=models.IntegerField(default=90),
        ),
    ]
