# Generated by Django 2.1.5 on 2019-10-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_vrheadsetrent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrheadsetrent',
            name='price',
            field=models.IntegerField(default=96),
        ),
    ]
